sources:
  - name: raw
    tables:
      - name: submissions
        external:
          location: /Users/andrea/Desktop/PhD/Data/Pipeline/reddit/data_trial/parquet_submissions
          using: 'parquet'
          partitions:
            - name: year
              data_type: int
            - name: month
              data_type: int
        columns:
          - name: author
            data_type: string
          - name: subreddit
            data_type: string
          - name: score
            data_type: bigint
          - name: created_utc
            data_type: bigint
          - name: title
            data_type: string
          - name: id
            data_type: string
          - name: num_comments
            data_type: bigint
          - name: selftext
            data_type: string
          - name: media
            data_type: boolean
          - name: year
            data_type: int
          - name: month
            data_type: int