warehouse:        
  target: local
  outputs:
    local:
      type: spark
      method: session
      schema: default     
      host: NA            
      threads: 1            
      server_side_parameters:
        "spark.master": "local[1]"
        "spark.driver.memory": "1g"
        "spark.sql.catalogImplementation": "hive"
        "spark.sql.warehouse.dir": "{{ env_var('SPARK_WAREHOUSE_DIR') }}"
        "spark.hadoop.hive.metastore.warehouse.dir": "{{ env_var('SPARK_WAREHOUSE_DIR') }}"
        "spark.driver.extraJavaOptions": "-Dderby.system.home={{ env_var('DERBY_SYSTEM_HOME') }}"
